// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'collection-open-matrix'
  | 'fields-dialog-title'
  | 'matrix-title'
  | 'menu-manage-fields'
  | 'menu-open-matrix'
  | 'section-head'
  | 'section-sidenav';
